{{- range $key, $svc := .Values.services }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ $svc.name }}
  namespace: ecommerce
  labels:
    app: {{ $svc.name }}
spec:
  selector:
    app: {{ $svc.name }}
  ports:
    - protocol: TCP
      port: {{ $svc.port }}
      targetPort: {{ $svc.port }}
  type: {{ $svc.serviceType | default "ClusterIP" }}
{{- end }}