{{- range $key, $svc := .Values.services }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ $svc.name }}
  namespace: ecommerce
  labels:
    app: {{ $svc.name }}
  {{- if eq ($svc.serviceType | default "ClusterIP") "LoadBalancer" }}
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-scheme: internet-facing
    service.beta.kubernetes.io/aws-load-balancer-type: nlb
  {{- end }}
spec:
  selector:
    app: {{ $svc.name }}
  ports:
    - protocol: TCP
      port: {{ $svc.port }}
      targetPort: {{ $svc.port }}
  type: {{ $svc.serviceType | default "ClusterIP" }}
{{- end }}